project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

execute:
  cache: true
  freeze: auto

website:
  title: "mccv"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - overview.qmd
      - getting_started.qmd
      - find_confounding.qmd
      - mccv_robust.qmd
      - mccv_power.qmd
      - mccv_parameters.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



