project:
  type: website
  render:
    - "*.ipynb"
    - "*.qmd"
  output-dir: docs

website:
  title: "mccv"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Generating_Datasets_For_MCCV.ipynb
        text: Biomarker Datasets
      - href: Running_Biomarker_Predictions_By_MCCV.ipynb
        text: Biomarker Predictions

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



